### ISSUE TITLE
Pattern with Stroage

### ISSUE THREAD

**Issue by VB10** [ragokan/okito#1]
https://github.com/ragokan/okito/blob/a0b41f1420baa5b09e4d7371f82da796059ebb46/lib/bin/okito_storage/modules/okito_io_storage.dart#L7

öncelikle eline sağık bence çok tatlı olmuş tüm katmanlar kendin yazmış olman tüm patternleri nice to have.
 -Stroage işlemlerini bir strategy pattern yapsak yarın yeni bir alan gelse misal nosql sambas, realm vs hepsınde ne tarz methodlar yapacağımız belirli olsa rahatlıkla projeyi ona evirebilsek contr vs içinde çok iyi olabilir vexanadaki bu örneğe bakabilrisin.

Eline sağık iyi çalışmalar

**Comment by ragokan** [comment]
> https://github.com/ragokan/okito/blob/a0b41f1420baa5b09e4d7371f82da796059ebb46/lib/bin/okito_storage/modules/okito_io_storage.dart#L7
> 
> öncelikle eline sağık bence çok tatlı olmuş tüm katmanlar kendin yazmış olman tüm patternleri nice to have.
> -Stroage işlemlerini bir strategy pattern yapsak yarın yeni bir alan gelse misal nosql sambas, realm vs hepsınde ne tarz methodlar yapacağımız belirli olsa rahatlıkla projeyi ona evirebilsek contr vs içinde çok iyi olabilir vexanadaki bu örneğe bakabilrisin.
> 
> Eline sağık iyi çalışmalar

Evet aslında bu storage çok şekillenecek, daha 1. gününde, ilk amacım sadece hız ve sağlamlıktı, bu özellikleri de ana hatlar bittiği gibi eklemeye başlayacağım, geri bildirim için çok teşekkür ederim :)
